### ISSUE TITLE
API.AI Agent configuration does not save in configuration file

### ISSUE THREAD

**Issue by slahiri** [technocreatives/node-red-contrib-apiai#1]
I am trying to use the apiai palette with node-red. When I try to save the agent configuration, it does not save the info in the flow file.

<img width="495" alt="screen shot 2017-01-15 at 1 14 36 am" src="https://cloud.githubusercontent.com/assets/887281/21960635/0fab5148-dac0-11e6-9789-03b1683f84f2.png">

The flow file agent configuration looks like
```
    {
        "id": "cec58ffa.a5ca1",
        "type": "apiai-agent",
        "z": ""
    }
```
Logs:
```
15 Jan 01:17:45 - [error] [apiai-agent:4dd8f7dc.afbe88] Error: 'clientAccessToken' cannot be empty.
15 Jan 01:17:45 - [error] [apiai-text:2ca583fb.030bdc] node-red-contrib-apiai:Missing Api.ai agent
```

**Comment by chrisgarmon** [comment]
I'm having the same problem.

**Comment by sichangi** [comment]
Same here

**Comment by eamigoni** [comment]
Same here

**Comment by oskarhagberg** [comment]
Tested on node-red v0.16.2 and Node.js v6.9.1 and it seems to be working fine. 

Important to make sure there is a token string in the Access token field, below the name field.

**Comment by chrisgarmon** [comment]
It still won't allow you to add any API keys. It resets after each save.

**Comment by oskarhagberg** [comment]
It's helpful if you share your node-red and node.js versions.
